/* Allegro datafile object indexes, produced by grabber v4.2.1, MSVC */
/* Datafile: d:\Instalables\Proyectos\Programacion DOS\entorno DJGPP DOS\env\test\DATOS.DAT */
/* Date: Fri Jun 13 10:14:36 2025 */
/* Do not hand edit! */

#define ALLEY_PCX                        0        /* BMP  */
#define ALLEYCAT_MID                     1        /* MIDI */
#define ALLEYTHE_WAV                     2        /* SAMP */
#define BEGE_PCX                         3        /* BMP  */
#define BG0_TMX                          4        /* DATA */
#define BG10_TMX                         5        /* DATA */
#define BG11_TMX                         6        /* DATA */
#define BG12_TMX                         7        /* DATA */
#define BG1_TMX                          8        /* DATA */
#define BG2_TMX                          9        /* DATA */
#define BG3_TMX                          10       /* DATA */
#define BG4_TMX                          11       /* DATA */
#define BG5_0_TMX                        12       /* DATA */
#define BG5_1_TMX                        13       /* DATA */
#define BG5_TMX                          14       /* DATA */
#define BG6_TMX                          15       /* DATA */
#define BG7_TMX                          16       /* DATA */
#define BG8_TMX                          17       /* DATA */
#define BG9_TMX                          18       /* DATA */
#define BINCAT_PCX                       19       /* BMP  */
#define BLUE_KEY_PCX                     20       /* BMP  */
#define CAT1_PCX                         21       /* BMP  */
#define CAT2_PCX                         22       /* BMP  */
#define CAT3_PCX                         23       /* BMP  */
#define CAT4_PCX                         24       /* BMP  */
#define CAT5_PCX                         25       /* BMP  */
#define CAT6_PCX                         26       /* BMP  */
#define CAT7_PCX                         27       /* BMP  */
#define CHEESE_PCX                       28       /* BMP  */
#define CLOTHES1_PCX                     29       /* BMP  */
#define CLOTHES2_PCX                     30       /* BMP  */
#define DIE_WAV                          31       /* SAMP */
#define DOG1_PCX                         32       /* BMP  */
#define DOG2_PCX                         33       /* BMP  */
#define DOG3_PCX                         34       /* BMP  */
#define DOG4_PCX                         35       /* BMP  */
#define DOG_PCX                          36       /* BMP  */
#define DOG_WAV                          37       /* SAMP */
#define ENEM1_10_PCX                     38       /* BMP  */
#define ENEM1_11_PCX                     39       /* BMP  */
#define ENEM1_1_PCX                      40       /* BMP  */
#define ENEM1_2_PCX                      41       /* BMP  */
#define ENEM1_3_PCX                      42       /* BMP  */
#define ENEM1_4_PCX                      43       /* BMP  */
#define ENEM1_5_PCX                      44       /* BMP  */
#define ENEM1_6_PCX                      45       /* BMP  */
#define ENEM1_7_PCX                      46       /* BMP  */
#define ENEM1_8_PCX                      47       /* BMP  */
#define ENEM1_9_PCX                      48       /* BMP  */
#define ENEM1D_PCX                       49       /* BMP  */
#define ENEM2_10_PCX                     50       /* BMP  */
#define ENEM2_11_PCX                     51       /* BMP  */
#define ENEM2_1_PCX                      52       /* BMP  */
#define ENEM2_2_PCX                      53       /* BMP  */
#define ENEM2_3_PCX                      54       /* BMP  */
#define ENEM2_4_PCX                      55       /* BMP  */
#define ENEM2_5_PCX                      56       /* BMP  */
#define ENEM2_6_PCX                      57       /* BMP  */
#define ENEM2_7_PCX                      58       /* BMP  */
#define ENEM2_8_PCX                      59       /* BMP  */
#define ENEM2_9_PCX                      60       /* BMP  */
#define ENEM2D_PCX                       61       /* BMP  */
#define ENEM3_10_PCX                     62       /* BMP  */
#define ENEM3_11_PCX                     63       /* BMP  */
#define ENEM3_1_PCX                      64       /* BMP  */
#define ENEM3_2_PCX                      65       /* BMP  */
#define ENEM3_3_PCX                      66       /* BMP  */
#define ENEM3_4_PCX                      67       /* BMP  */
#define ENEM3_5_PCX                      68       /* BMP  */
#define ENEM3_6_PCX                      69       /* BMP  */
#define ENEM3_7_PCX                      70       /* BMP  */
#define ENEM3_8_PCX                      71       /* BMP  */
#define ENEM3_9_PCX                      72       /* BMP  */
#define ENEM3D_PCX                       73       /* BMP  */
#define ENEMY1_PCX                       74       /* BMP  */
#define ENEMY2_PCX                       75       /* BMP  */
#define ENEMY3_PCX                       76       /* BMP  */
#define FALL_WAV                         77       /* SAMP */
#define FINAL_PCX                        78       /* BMP  */
#define GIRL_PCX                         79       /* BMP  */
#define HEAD_PCX                         80       /* BMP  */
#define HEART_PCX                        81       /* BMP  */
#define HIT_WAV                          82       /* SAMP */
#define KEY_PCX                          83       /* BMP  */
#define LEVELS_CSV                       84       /* DATA */
#define LIFEBAR_PCX                      85       /* BMP  */
#define LIVES_PCX                        86       /* BMP  */
#define MAIN10_PCX                       87       /* BMP  */
#define MAIN11_PCX                       88       /* BMP  */
#define MAIN12_PCX                       89       /* BMP  */
#define MAIN1_PCX                        90       /* BMP  */
#define MAIN2_PCX                        91       /* BMP  */
#define MAIN3_PCX                        92       /* BMP  */
#define MAIN4_PCX                        93       /* BMP  */
#define MAIN5_PCX                        94       /* BMP  */
#define MAIN6_PCX                        95       /* BMP  */
#define MAIN7_PCX                        96       /* BMP  */
#define MAIN8_PCX                        97       /* BMP  */
#define MAIN9_PCX                        98       /* BMP  */
#define MAIN_PCX                         99       /* BMP  */
#define MAIND_PCX                        100      /* BMP  */
#define METAL_WAV                        101      /* SAMP */
#define MOTO_WAV                         102      /* SAMP */
#define PHONE_PCX                        103      /* BMP  */
#define PUNCH2_WAV                       104      /* SAMP */
#define PUNCH_WAV                        105      /* SAMP */
#define ROGERR_MID                       106      /* MIDI */
#define TILES_PCX                        107      /* BMP  */
#define VESPINO2_PCX                     108      /* BMP  */
#define VESPINO3_PCX                     109      /* BMP  */
#define VESPINO_PCX                      110      /* BMP  */
#define VOICE_WAV                        111      /* SAMP */
#define WIN_MID                          112      /* MIDI */

