#define TILES_BMP                     	0   	//BMP 
#define ALLEY_BMP                     	1   	//BMP 
#define FINAL_BMP                     	2   	//BMP 
#define PLAYER_BMP                    	3   	//BMP 
#define MAIND_BMP                     	4   	//BMP 
#define HEAD_BMP                      	5   	//BMP 
#define LIFEBAR_BMP                   	6   	//BMP 
#define ENEMY1_BMP                    	7   	//BMP 
#define ENEMY2_BMP                    	8   	//BMP 
#define ENEMY3_BMP                    	9   	//BMP 
#define ENEM1D_BMP                    	10  	//BMP 
#define ENEM2D_BMP                    	11  	//BMP 
#define ENEM3D_BMP                    	12  	//BMP 
#define VESPINO_BMP                   	13  	//BMP 
#define VESPINO2_BMP                  	14  	//BMP 
#define VESPINO3_BMP                  	15  	//BMP 
#define GIRL_BMP                      	16  	//BMP 
#define KEY_BMP                       	17  	//BMP 
#define BLUE_KEY_BMP                  	18  	//BMP 
#define CHEESE_BMP                    	19  	//BMP 
#define CAT_BMP                       	20  	//BMP 
#define DOG_BMP                       	21  	//BMP 
#define HEART_BMP                     	22  	//BMP 
#define CLOTHES1_BMP                  	23  	//BMP 
#define CLOTHES2_BMP                  	24  	//BMP 
#define BINCAT_BMP                    	25  	//BMP 
#define PHONE_BMP                     	26  	//BMP 
#define BG0_TMX                       	27  	//DATA
#define BG1_TMX                       	28  	//DATA
#define BG2_TMX                       	29  	//DATA
#define BG3_TMX                       	30  	//DATA
#define BG4_TMX                       	31  	//DATA
#define BG5_TMX                       	32  	//DATA
#define BG5_0_TMX                     	33  	//DATA
#define BG5_1_TMX                     	34  	//DATA
#define BG6_TMX                       	35  	//DATA
#define BG7_TMX                       	36  	//DATA
#define BG8_TMX                       	37  	//DATA
#define BG9_TMX                       	38  	//DATA
#define BG10_TMX                      	39  	//DATA
#define BG11_TMX                      	40  	//DATA
#define BG12_TMX                      	41  	//DATA
#define LEVELS_CSV                    	42  	//DATA
#define ROGERR_MID                    	43  	//MIDI
#define ALLEYCAT_MID                  	44  	//MIDI
#define WIN_MID                       	45  	//MIDI
#define ALLEYTHEME_WAV                	46  	//SAMP
#define HIT_WAV                       	47  	//SAMP
#define DOG_WAV                       	48  	//SAMP
#define PUNCH_WAV                     	49  	//SAMP
#define PUNCH2_WAV                    	50  	//SAMP
#define VOICE_WAV                     	51  	//SAMP
#define FALL_WAV                      	52  	//SAMP
#define DIE_WAV                       	53  	//SAMP
#define MOTO_WAV                      	54  	//SAMP
#define METAL_WAV                     	55  	//SAMP
#define ENEMY_KILL_WAV                	56  	//SAMP
#define PALETE_TILES_BMP              	57  	//PAL 
#define PALETE_ALLEY_BMP              	58  	//PAL 
#define PALETE_FINAL_BMP              	59  	//PAL 
